#yaml file
name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
  SERVICE_NAME: ${{secrets.GCLOUD_SA_EMAIL}}
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCLOUD_SA_KEY }}'
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
        
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'
          project_id: ${{ env.PROJECT_ID }}
          service_account_email: ${{env.SERVICE_NAME}}
          service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
          
      - name: Build and Deploy
        run: |
          gcloud builds submit \
            --tag gcr.io/${{ env.PROJECT_ID }}/csv-to-parquet-image
          gcloud run deploy csv-to-parquet \
            --image gcr.io/${{ env.PROJECT_ID }}/csv-to-parquet-image:latest \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --project ${{ env.PROJECT_ID }}
