on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_email: ${{ secrets.GCLOUD_SA_EMAIL }}
          service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
          export_default_credentials: true

      - name: Build and push Docker image
        run: |
          gcloud auth configure-docker
          docker build -t gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/csv-to-parquet .
          docker push gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/csv-to-parquet

      - name: Deploy the Cloud Run service
        run: gcloud run deploy csv-to-parquet --image=gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/csv-to-parquet --region=us-central1 --platform=managed
