name: Cloud Run Deployment

on:
  push:
    branches:
     - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_email: ${{ secrets.GCLOUD_SA_EMAIL }}
          service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
          export_default_credentials: true

      - name: Build the Docker image
        run: docker builds submit -t gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/csv-to-parquet-image .

      - name: Deploy the Cloud Run service
        run: gcloud run deploy csv-to-parquet --image=gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/csv-to-parquet-image:latest --region=us-central1 --platform=managed
