#yaml file
name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
  SERVICE_NAME: ${{secrets.GCLOUD_SA_EMAIL}}
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/326614876881/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: githubworkloadidentity@meta-sensor-380711.iam.gserviceaccount.com
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
        
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: 'projects/326614876881/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: githubworkloadidentity@meta-sensor-380711.iam.gserviceaccount.com
          
      - name: Build and Deploy
        run: |
          gcloud builds submit \
            --tag gcr.io/${{ env.PROJECT_ID }}/csv-to-parquet-image
          gcloud run deploy csv-to-parquet \
            --image gcr.io/${{ env.PROJECT_ID }}/csv-to-parquet-image:latest \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --project ${{ env.PROJECT_ID }}
