on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_email: ${{ secrets.GCLOUD_SA_EMAIL }}
          service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
          export_default_credentials: true

      - name: Configure gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '342.0.0'
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_email: ${{ secrets.GCLOUD_SA_EMAIL }}
          service_account_key: ${{ secrets.GCLOUD_SA_KEY }}

      - name: Build and publish image to GCR
        uses: carbonchain/action-container-registry@v1.1
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          dockerfile: .
          image: gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/csv-to-parquet
          service_account_key: ${{ secrets.GCLOUD_SA_KEY }}

      - name: Deploy the Cloud Run service
        run: gcloud run deploy csv-to-parquet --image=gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/csv-to-parquet --region=us-central1 --platform=managed
