name: cloud-run-deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v1.1.0
        with:
          version: '2.303.0'
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
          export_default_credentials: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-options: network=host

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: REGION-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT_ID }}/my-cloud-run-service/my-cloud-run-service:TAG
          build-args: |
            REGISTRY=REGION-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT_ID }}
            REPOSITORY=my-cloud-run-service
            IMAGE=my-cloud-run-service
            TAG=${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloud-run@v0.4.0
        with:
          image: REGION-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT_ID }}/my-cloud-run-service/my-cloud-run-service:TAG
          platform: managed
          region: us-central1
          service: my-cloud-run-service
          revision: ${{ github.sha }}
          allow-unauthenticated: true
