name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t gcr.io/${{ secrets.GCLOUD_PROJECT-ID }}[PROJECT-ID]/csv-to-parquet .

      - name: Authenticate with Google Cloud
        uses: google-github-actions/setup-gcloud@V1
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_SA_KEY }}

      - name: Push Docker image to GCR
        run: |
          docker push gcr.io/${{ secrets.GCLOUD_PROJECT-ID }}/csv-to-parquet

      - name: Deploy image to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          image: gcr.io/${{ secrets.GCLOUD_PROJECT-ID }}/csv-to-parquet
          platform: managed
          region: us-central1
          service_name: csv-to-parquet
          allow_unauthenticated: true
