name: Cloud Run Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: YOUR_PROJECT_ID
          service_account_email: ${{ secrets.GCLOUD_SA_EMAIL}}
          service_account_key: ${{ secrets.GCLOUD_SA_KEY}}
      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCLOUD_PROJECT_ID}}/csv-to-parquet:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCLOUD_PROJECT_ID}}/csv-to-parquet:${{ github.sha }}
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-cloud-run-service `
            --image gcr.io/${{ env.PROJECT_ID }}/csv-to-parquet:${{ github.sha }} `
            --region us-central1 `
            --platform managed
