name: Cloud Run Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_email: ${{ secrets.GCLOUD_SA_EMAIL }}
          service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
          export_default_credentials: true

      #- name: Log in to Docker Hub
       # uses: docker/login-action@v1
        #with:
          #username: ${{ secrets.DOCKER_USERNAME }}
          #password: ${{ secrets.DOCKER_PASSWORD }}
          # Authenticate with gcloud
      - name: Configure gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '342.0.0'
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_email: ${{ secrets.GCLOUD_SA_EMAIL }}
          service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
      - run: gcloud auth configure-docker
      
      -  name: Pull Docker image
         run: docker pull gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/csv-to-parquet

  # Build and push the Docker image
      #- name: Build and push Docker image
        #run: |
         #docker build -tag gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/csv-to-parquet .
         #docker push gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/csv-to-parquet

      #- name: Push the Docker image to Google Container Registry
        #run: |
         # echo ${{ secrets.GCLOUD_SA_KEY }} | docker login -u _json_key --password-stdin https://gcr.io
          #docker push gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/csv-to-parquet


      - name: Deploy the Cloud Run service
        run: gcloud run deploy csv-to-parquet --image=gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/csv-to-parquet--region=us-central1 --platform=managed
