name: Cloud Run Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_email: ${{ secrets.GCLOUD_SA_EMAIL }}
          service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        uses: docker/setup-docker@v1

      - name: Build the Docker image
        run: docker build -t gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/csv_to_parquetfile .

      - name: Push the Docker image to Google Container Registry
        run: |
          echo ${{ secrets.GCLOUD_SA_KEY }} | docker login -u _json_key --password-stdin https://gcr.io
          docker push gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/csv_to_parquetfile

      - name: Deploy the Cloud Run service
        run: gcloud run deploy csv-to-parquet   --image gcr.io/meta-sensor-380711/csv_to_parquetfile   --platform managed   --region us-central1   --port 8080   --allow-unauthenticated
